"""initial

Revision ID: 422922146a6f
Revises:
Create Date: 2023-09-21 18:04:20.860085

"""
from datetime import UTC, datetime

import sqlalchemy as sa
from alembic import op

from app.core.security import get_password_hash

# revision identifiers, used by Alembic.
revision = '422922146a6f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('bookID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('authors', sa.String(), nullable=False),
    sa.Column('book_created_at', sa.DateTime(timezone=True), default=datetime.now(tz=UTC)),
    sa.PrimaryKeyConstraint('bookID')
    )
    op.create_index(op.f('ix_books_bookID'), 'books', ['bookID'], unique=False)
    op.create_table('users',
    sa.Column('userID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('surname', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('user_type', sa.String(length=10), nullable=False),
    sa.Column('user_created_at', sa.DateTime(timezone=True), default=datetime.now(tz=UTC)),
    sa.PrimaryKeyConstraint('userID'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('hashed_password')
    )
    op.create_index(op.f('ix_users_userID'), 'users', ['userID'], unique=False)
    op.create_table('book_action',
    sa.Column('statusID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('bookID', sa.Integer(), nullable=False),
    sa.Column('type_action', sa.String(length=10), nullable=False),
    sa.Column('time_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_finished', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bookID'], ['books.bookID'], name='fk__book_status__books'),
    sa.ForeignKeyConstraint(['userID'], ['users.userID'], name='fk__book_status__users'),
    sa.PrimaryKeyConstraint('statusID')
    )
    op.create_index(op.f('ix_book_action_statusID'), 'book_action', ['statusID'], unique=False)
    op.create_table('book_queries',
    sa.Column('queryID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('bookID', sa.Integer(), nullable=False),
    sa.Column('order_type', sa.String(length=10), nullable=False),
    sa.Column('action_type', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['bookID'], ['books.bookID'], name='fk__queries_BookID__books'),
    sa.ForeignKeyConstraint(['userID'], ['users.userID'], name='fk__queries_UserID__users'),
    sa.PrimaryKeyConstraint('queryID')
    )
    op.create_index(op.f('ix_book_queries_queryID'), 'book_queries', ['queryID'], unique=False)

    op.execute(f"INSERT INTO users (first_name, surname, email, user_type, hashed_password) VALUES ('Иван', 'Иванов', 'example123@example.ru', 'Admin', '{get_password_hash('Qwerty123.')}');")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_queries_queryID'), table_name='book_queries')
    op.drop_table('book_queries')
    op.drop_index(op.f('ix_book_action_statusID'), table_name='book_action')
    op.drop_table('book_action')
    op.drop_index(op.f('ix_users_userID'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_books_bookID'), table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###
